const data = {
    products: [
      {
        _id: '1',
        name: 'Chicken Burger',
        category: 'Chicken',
        image: '/images/burger1.jpg',
        price: 120,
        countInStock: 10,
        brand: 'Burger King',
        rating: 4.5,
        numReviews: 10,
        description: 'Chicken Burger with mustard sauce',
      },
      {
        _id: '2',
        name: 'Beef Burger',
        category: 'Beef',
        image: '/images/burger2.jpg',
        price: 140,
        countInStock: 20,
        brand: 'Burger King',
        rating: 4.0,
        numReviews: 10,
        description: 'Beef Burger with mustard sauce',
      },
      {
        _id: '3',
        name: 'Beef Cheese Burger',
        category: 'Beef',
        image: '/images/burger3.jpg',
        price: 220,
        countInStock: 0,
        brand: 'Burger King',
        rating: 4.8,
        numReviews: 17,
        description: 'Beef Burger with mustard sauce and sliced cheese',
      },
      {
        _id: '4',
        name: 'Chicken Sausage Burger',
        category: 'Chicken',
        image: '/images/burger1.jpg',
        price: 260,
        countInStock: 15,
        brand: 'Burger King',
        rating: 4.5,
        numReviews: 14,
        description: 'Chicken Burger with mustard sauce, sliced cheese and sausage',
      },
      {
        _id: '5',
        name: 'Beef Sausage Burger',
        category: 'Beef',
        image: '/images/burger2.jpg',
        price: 270,
        countInStock: 5,
        brand: 'Burger King',
        rating: 4.5,
        numReviews: 10,
        description: 'Beef Burger with mustard sauce, sliced cheese and sausage',
      },
      {
        _id: '6',
        name: 'King Burger',
        category: 'Specials',
        image: '/images/burger3.jpg',
        price: 340,
        countInStock: 12,
        brand: 'Burger King',
        rating: 4.5,
        numReviews: 15,
        description: 'Burger with double patty of beef and chicken with sliced cheese and mustard sauce',
      },
    ],
  };
  export default data;